### ISSUE TITLE
There is something wrong with the command Register

### ISSUE THREAD

**Issue by liangtj** [Binly42/agenda-go#4]
Yesterday before i  sent a pr,   the regiester command worked well as i thought,  but now i found that it throw a error unexpectedly when i pull ur branch and run. The error show such a statement : " Error[register]： runtime error: invalid memory address or nil pointer dereference", but what i only to do in the file named **register.go** is to get the flags and call 2 function **_MakeUserInfo_** & **_RegisterUser_** . So it is impossible for me to trigger the error. **Debug as soon as possible and what is more is that u need to write the MD file now!**

**Comment by Binly42** [comment]
...... 我就刚还想给你说不用发了..., 我刚见你还没发, 就去试着复现, 结果发现确实是我遗漏了..... 我待会推一个 fix

**Comment by liangtj** [comment]
**i FUCK U**
**馬鹿野郎**
**丢雷楼某** @Binly42

**Comment by Binly42** [comment]
不会用 github, 就刚才推的那个, 但是 issue号(手写的...) 没对上

另外, 写什么 Markdown ? 是说设计文档吗? 是的话那我随便糊一个 (但是显然 MD 是不会有的了

**Comment by liangtj** [comment]
完全ojbk

**Comment by liangtj** [comment]
你push了？？我这里还是有那个error啊

**Comment by liangtj** [comment]
OK  all work well now , thanks

**Comment by Binly42** [comment]
对呀, 就是最新的那个, "Fix issue#1" 的那个; 

你是说错误一模一样 ? 是的话不应该啊, 发一下进一步 log 的情况.
