### ISSUE TITLE
看看什么时候把 Usage 和 UI 部分的 Overview 补一下吧

### ISSUE THREAD

**Issue by Binly42** [Binly42/agenda-go#7]
( 我刚刚随便用了一下, 感觉 bug 超多.... 但是无所谓啦
@LIANGTJ

**Comment by liangtj** [comment]
所以我只是最基础的写完而已啊，现在我先把md写了，回去再进一步维护修复bug 
@Binly42

**Comment by Binly42** [comment]
Finished with PR #8 .
